version: '3.8'

services:
  pdf_chatbot:
    build:
      context: ./pdf_chatbot
    ports:
      - "8001:8000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
