version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webpage_demo:
    build:
      context: ./webpage_demo
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  pdf_chatbot:
    build:
      context: ./pdf_chatbot
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  ai_summary:
    build:
      context: ./ai_summary
    ports:
      - "8002:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  ai_cover:
    build:
      context: ./ai_cover
    ports:
      - "8003:8000"
    command: gunicorn AI_cover.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  ai_image:
    build:
      context: ./ai_image
    ports:
      - "8004:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: