name: Deploy Django to NCP with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install expect
      run: sudo apt-get install -y expect

    - name: Sync and Deploy
      run: |
        expect <<- EOF
          spawn ssh -o StrictHostKeyChecking=no -l ${{ secrets.NCP_USER }} -p ${{ secrets.NCP_PORT }} ${{ secrets.NCP_ADDRESS }}
          expect "password:"
          send "$${{ secrets.NCP_PASSWORD }}\r"
          expect "$ "
          send "cd /home/test/Docker_MSA_test\r"
          expect "$ "
          send "sudo chown -R $USER:$USER .\r"
          expect "$ "
          send "sudo chmod -R 755 .\r"
          expect "$ "
          send "git config --global --add safe.directory /home/test/Docker_MSA_test\r"
          expect "$ "
          send "git pull --recurse-submodules=on-demand origin main\r"
          expect "$ "
          send "sudo docker-compose build\r"
          expect "$ "
          send "sudo docker-compose down\r"
          expect "$ "
          send "sudo docker-compose up -d\r"
          expect "$ "
          send "exit\r"
          expect eof
        EOF