name: Deploy Django to NCP with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.NCP_SSH }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.NCP_PORT }} ${{ secrets.NCP_USER }}@${{ secrets.NCP_ADDRESS }} << 'EOF'
          cd /home/test/Docker_MSA_test
          sudo chown -R $USER:$USER .
          sudo chmod -R 755 .
          git config --global --add safe.directory /home/test/Docker_MSA_test
          git pull --recurse-submodules=on-demand origin main
          sudo docker-compose build
          sudo docker-compose down
          sudo docker-compose up -d
        EOF