name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        NCP_PASSWORD: ${{ secrets.NCP_PASSWORD }}
      run: |
        sshpass -p "$NCP_PASSWORD" ssh -o StrictHostKeyChecking=no -l ${{ secrets.NCP_USER }} -p ${{ secrets.NCP_PORT }} ${{ secrets.NCP_ADDRESS }} << 'EOF'
          cd /home/test/Docker_MSA_test
          sudo chown -R $USER:$USER .
          sudo chmod -R 755 .
          git stash
          git config --global --add safe.directory /home/test/Docker_MSA_test
          git pull --recurse-submodules=on-demand origin main
           git submodule update --init --recursive
          sudo docker-compose build
          sudo docker-compose down
          sudo docker-compose up -d
        EOF