name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.NCP_SSH }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -l ${{ secrets.NCP_USER }} -p ${{ secrets.NCP_PORT }} ${{ secrets.NCP_HOST }} << 'EOF'
          cd /home/test/Docker_MSA_test
          sudo chown -R $USER:$USER .
          sudo chmod -R 755 .
          git config --global --add safe.directory /home/test/Docker_MSA_test
          git pull --recurse-submodules=on-demand origin main
          sudo docker-compose build
          sudo docker-compose down
          sudo docker-compose up -d
        EOF